# Generated by Django 3.2.7 on 2021-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=250)),
                ('news_score', models.IntegerField(default=0)),
                ('news_title', models.CharField(max_length=250)),
                ('news_type', models.CharField(max_length=250)),
                ('news_url', models.URLField()),
                ('news_time', models.DateTimeField(auto_now=True)),
                ('is_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
